-- 코드를 입력하세요
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C
WHERE C.CAR_TYPE = '세단' AND C.CAR_ID IN (SELECT H.CAR_ID
                  FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
                  WHERE MONTH(H.START_DATE) = '10')
ORDER BY C.CAR_ID DESC;