-- 코드를 입력하세요
SELECT T2.FOOD_TYPE AS FOOD_TYPE
     , T2.REST_ID AS REST_ID
     , T2.REST_NAME AS REST_NAME
     , T2.FAVORITES AS FAVORITES
FROM (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
      FROM REST_INFO
      GROUP BY FOOD_TYPE) AS T1, REST_INFO T2 
WHERE T1.FOOD_TYPE = T2.FOOD_TYPE AND T1.FAVORITES = T2.FAVORITES
ORDER BY FOOD_TYPE DESC;