-- 코드를 입력하세요
SELECT USER.USER_ID, USER.NICKNAME, BOARD.TOTAL_SALES
FROM (SELECT WRITER_ID, SUM(PRICE) AS 'TOTAL_SALES'
      FROM USED_GOODS_BOARD
      WHERE STATUS LIKE 'DONE'
      GROUP BY WRITER_ID
      HAVING SUM(PRICE) >= 700000
     ) BOARD, USED_GOODS_USER USER
WHERE BOARD.WRITER_ID = USER.USER_ID
ORDER BY BOARD.TOTAL_SALES ASC;