-- 코드를 입력하세요
SELECT G.USER_ID, G.NICKNAME, SUM(B.PRICE) TOTAL_PRICE
FROM USED_GOODS_BOARD B, USED_GOODS_USER G
WHERE B.WRITER_ID = G.USER_ID AND B.STATUS = 'DONE'
GROUP BY G.USER_ID
HAVING SUM(B.PRICE) >= 700000
ORDER BY TOTAL_PRICE;