-- 코드를 입력하세요
SELECT BO.CATEGORY AS 'CATEGORY', SUM(SA.SALES) AS 'TOTAL_SALES'
FROM BOOK_SALES SA, BOOK BO
WHERE BO.BOOK_ID = SA.BOOK_ID AND DATE_FORMAT(SA.SALES_DATE,'%Y-%m') = '2022-01' 
GROUP BY BO.CATEGORY
ORDER BY BO.CATEGORY ASC;